### ISSUE TITLE
Eコマースのチュートリアルで英語版チュートリアルの指示通りにgatsby-config.jsを設定するとエラーが発生する

### ISSUE THREAD

**Issue by naoya7076** [gatsbyjs/gatsby-ja#132]
#89 
## 概要
現在、[eコマースのチュートリアル](https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/)の翻訳を進めています。
Installing the StripeJS plugin
というセクションについてなのですが指示通りに`gatsby-config.js`を設定するとエラーが発生します。
この場合は`gatsby-config.js`をはどちらにすればいいでしょうか？
## 詳細
英語版チュートリアルの`gatsby-config.js`
```js:title=gatsby-config.js
module.exports = {
  siteMetadata: {
    title: "Gatsby E-Commerce Starter",
  },
  plugins: ["gatsby-plugin-react-helmet", "gatsby-plugin-stripe"],
}
```
この通りに`gatsby-config.js`を設定して`npm run develop`を実行すると以下のエラーが発生します
![image](https://user-images.githubusercontent.com/32981554/73129844-ebaf5b80-402f-11ea-97c5-7274b17ec692.png)

しかし、このように設定すると動作します。
```js:title=gatsby-config.js
module.exports = {
  siteMetadata: {
    title: `Gatsby E-Commerce Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    `gatsby-plugin-stripe`
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
```

![image](https://user-images.githubusercontent.com/32981554/73129866-67110d00-4030-11ea-95ba-854ce2ef69c0.png)

## 資料
[私のeコマースチュートリアルのレポジトリ](https://github.com/naoya7076/ecommerce-gatsby)
[私の翻訳プロジェクトのプルリクエスト](https://github.com/gatsbyjs/gatsby-ja/pull/89)

**Comment by uetchy** [comment]
公式のドキュメントにPRを送る必要があるかもしれません。

https://github.com/gatsbyjs/gatsby/issues

こちらからIssue（英語）を投げてみてください。

**Comment by naoya7076** [comment]
Issue投げてみます！

**Comment by naoya7076** [comment]
IssueとPRを投げたので完了とします
https://github.com/gatsbyjs/gatsby/issues/20888
https://github.com/gatsbyjs/gatsby/pull/20889
