### ISSUE TITLE
Bug: PullRequest時のlabelWhenCreatedがエラーにより落ちる

### ISSUE THREAD

**Issue by bebetaro** [gatsbyjs/gatsby-ja#95]
### 現在の動作
PR時に走るlabelWhenCreatedがエラーにより落ちる
```
##[error]Invalid value for parameter 'issue_number': {"owner":"gatsbyjs","repo":"gatsby-ja","number":87} is NaN
##[error]Node run failed with exit code 1
```

### 期待する動作
`issue_number`にオブジェクトが渡され`NaN`となっているので、Numberが渡され適切にlabelWhenCreatedが走ること

### 備考
エラー分から察するに、
https://github.com/gatsbyjs/gatsby-ja/blob/master/.github/workflows/label-when-created.yml
の`const issue_number = context.issue;`を`const issue_number = context.issue.number;`にすれば直るのかと思いますが、いかがでしょうか？
それで良ければPR書かせていただきます。よろしくお願いします:bow:

**Comment by imbsky** [comment]
この問題は既に修正のPRを私が開いており、Gatsbyコアチームの対応待ちとなっています。

**Comment by imbsky** [comment]
https://github.com/gatsbyjs/gatsby-ja/pull/59

**Comment by bebetaro** [comment]
@imbsky そうだったのですね！見落としておりまして申し訳無いです:sweat: 既にご対応済みとのことでcloseします:bow:

**Comment by imbsky** [comment]
いえ、とんでもないです。とはいえ、まだ修正はされていないのでCloseする必要はないかと思います。

**Comment by imbsky** [comment]
This was temporarily solved by https://github.com/gatsbyjs/gatsby-ja/pull/117.
